name: flutter_widget_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  csv: ^5.0.2
  flutter_gif: ^0.0.4
  sqflite: ^2.2.2
  path_provider: ^2.0.15
  path: ^1.8.2
  volume_controller: ^2.0.6
  flutter_launcher_icons: ^0.13.0
  curved_navigation_bar: ^1.0.3 #latest version
  sensors_plus: ^1.2.2
  libphonenumber_plugin: ^0.3.1
  chat_bubbles: ^1.4.1
  connectivity_plus: ^2.2.1
  image_picker: ^0.8.8
  google_fonts: any
  animate_do: ^2.1.0
  flutter_slidable: ^3.0.0
  quickalert: ^1.0.0
  video_player: ^2.6.1
  flutter_zoom_drawer: ^3.1.1
  get: ^4.6.5
  stylish_bottom_bar: ^1.0.3
  collapsible_sidebar: ^2.0.5+1
  iconsax: ^0.0.8
  tab_container: ^2.0.0
  flutter_vector_icons: ^2.0.0
  qr_flutter: ^4.1.0
  web_browser: ^0.7.4
  flutter_web_browser: ^0.17.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
